# Data source settings
data:
  input_path: "/home/jh3439/project_pi_zy279/jh3439/saved_data"
  output_path: "/home/jh3439/project_pi_zy279/jh3439/simple-post-training/lm_sft/data/processed_data"
  dataset_name:
    - teknium/OpenHermes-2.5
    - SoftAge-AI/multi-turn_dataset
  train_split: 0.9

# Model settings
model:
  source_model_path: "/home/jh3439/project_pi_zy279/jh3439/saved_models"
  extended_model_path: "/home/jh3439/project_pi_zy279/jh3439/simple-post-training/lm_sft/data/processed_models"
  model_name: "meta-llama_Llama-3.1-8B"
  torch_dtype: "bfloat16"  # Options: float32, float16, bfloat16

template:
  path: "/home/jh3439/project_pi_zy279/jh3439/simple-post-training/lm_sft/scripts/template_format.json"

working_dir: "/home/jh3439/project_pi_zy279/jh3439/simple-post-training/lm_sft"
